apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: mongodbrs
  namespace: test-ns
spec:
  selector:
    matchLabels:
      app: mongodb
  template:
     metadata:
       name: mongodbpod
       labels:
         app: mongodb
     spec:
       containers:
       - name: mongo
         image: mongo
         ports:
         - containerPort: 27017
         env:
         - name: MONGO_INITDB_ROOT_USERNAME
           value: geetha
         - name: MONGO_INITDB_ROOT_PASSWORD
           value: geethapwd
         volumeMounts:
         - name: mongovol
           mountPath: /data/db
       volumes:
       - name: mongovol
         persistentVolumeClaim:
          claimName: mongopvc

---
apiVersion: v1
kind: Service
metadata:
  name: mongo
  namespace: test-ns
spec:
  type: ClusterIP
  selector:
    app: mongodb
  ports:
  - port: 27017
    targetPort: 27017
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongopvc
  namespace: test-ns
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
